### ISSUE TITLE
Last commit has broken installation in macOS

### ISSUE THREAD

**Issue by xilopaint** [ProtonVPN/protonvpn-cli#34]
This is what I got after 4d6805173ea749fcbd336e90b53d54964c61b75d:

```
$ sudo ./protonvpn-cli.sh -install
cp: /usr/bin/protonvpn-cli: Operation not permitted
ln: /usr/bin/pvpn: Operation not permitted
chown: /usr/bin/protonvpn-cli: No such file or directory
chown: /usr/bin/pvpn: No such file or directory
chmod: /usr/bin/protonvpn-cli: No such file or directory
chmod: /usr/bin/pvpn: No such file or directory
[*] Done.
```

**Comment by xilopaint** [comment]
Seemingly, **System Integrity Integrity Protection (SIP)** makes `/usr/bin` read-only but leaves `/usr/local` as read-write:

https://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled

**Comment by mazen160** [comment]
Hi @xilopaint 
I added a backward compatibility today for installation/uninstallation.

Please test it, if it goes well, I will suppress errors on next update.

**Comment by xilopaint** [comment]
```
$ sudo protonvpn-cli -c
/usr/local/bin/protonvpn-cli: line 1: /#!/usr/bin/env: No such file or directory
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5523, in <module>
ValueError: invalid literal for int() with base 10: '-e 0'
```

**Comment by xilopaint** [comment]
d4668a0a448ad2d27b3468ddb3c8ac592d25c26b added a typo in the shebang that caused the issue. #35 fixes it.

**Comment by mazen160** [comment]
Hi @xilopaint 

This should be fixed now. Please confirm when you can.

**Comment by xilopaint** [comment]
Errors suppressed.

**Comment by chrislarry** [comment]
my errors

 Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/cli.py", line 116, in cli
    connection.fastest(protocol)
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 149, in fastest
    disconnect(passed=True)
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 339, in disconnect
    manage_dns("restore")
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 612, in manage_dns
    oldhash = get_config_value("metadata", "resolvconf_hash")
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/utils.py", line 122, in get_config_value
    return config[group][key]
  File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'resolvconf_hash'
